version: "3.4"
services:
  app:
    build:
      context: .
      target: dev-stage
    command: ["npm", "start"]
    volumes:
    - .:/usr/src/
    - /usr/src/node_modules
    ports:
      - "3000:3000"
