version: "3.7"
services:
  app:
    build:
      context: .
      target: dev-stage
    command: ["npm", "start"]
    volumes:
    - .:/usr/src/
    - /usr/src/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
